### PR TITLE
ports/rx*/readme_threadx.txt: Update implementation information of in…

### PR DESCRIPTION
**Pull request by TakeoTakahashi2020**
Hello,  I checked the latest implementation about interrupt related information and update the readme_threadx.txt for RXv1/v2/v3.
It would be appreciated if you could double-check and update.  Thanks.

### CODE REVIEW

**Comment by goldscott** [comment]
Thanks @TakeoTakahashi2020! We will update the readmes internally and they will be available in our next release, scheduled for October. There is a release at the end of this month, but it is too late to make any changes now.

**Comment by TakeoTakahashi2020** [comment]
@goldscott   Thank you for picking up my PR.  I understand the release schedule.

**Comment by goldscott** [comment]
I'll close this PR. We have updated the readmes internally and they will be available in the next release in a few months.

**Comment by TakeoTakahashi2020** [comment]
@goldscott  OK,  Thanks.

**Pull request closed without merging**
